### ISSUE TITLE
Support for "stormish" icons

### ISSUE THREAD

**Issue by marianoarga** [darkskyapp/skycons#13]
There is no icons for lighting circunstances, like Storms.

**Comment by ironwallaby** [comment]
Correct. While adding one would be nice, I can tell you that I won't be doing it until Dark Sky supports lightning :)

Nonetheless, it's a notable omission, so I'm leaving this ticket open.

**Comment by arduino731** [comment]
cant wait let me know when release for thunderstorm due to api.openweather.

**Comment by drguildo** [comment]
I agree that these are a notable omission. In the mean time I suggest using `Skycons.WIND`.

**Comment by PedroD** [comment]
I agree that these are a notable omission.

**Comment by peternewman** [comment]
This repo has lightning, would you accept a PR to add it in (presumably without the colour bits given the discussion in https://github.com/darkskyapp/skycons/pull/8)?
https://github.com/galdiuz/skycons

**Comment by peternewman** [comment]
Or this adds some other stormy ones (but not thunder): https://github.com/Icelandair/skycons

**Comment by peternewman** [comment]
> This repo has lightning, would you accept a PR to add it in (presumably without the colour bits given the discussion in #8)?
> https://github.com/galdiuz/skycons

Hi @ironwallaby ,

You didn't particularly clarify in https://github.com/darkskyapp/skycons/pull/29#issuecomment-531323859 would you accept a PR to merge a B&W version of thunder from the Extension repo?

**Comment by ghost** [comment]
**Skycons** is no longer maintained; please fork to do any further work on it!
