### ISSUE TITLE
Don't user IDs

### ISSUE THREAD

**Issue by heidimark** [darkskyapp/skycons#19]
I would think utilizing class names for the canvas attribute rather than IDs would be preferable. As it is, the same icon cannot appear twice on a page as that would mean elements sharing the same ID. This practically impedes any ability to utilize this for a true forecast where multiple days may have the same weather.

**Comment by ironwallaby** [comment]
You aren't required to use `id` attributes: if you want to use something else, simply pass the DOM element, instead.
