### ISSUE TITLE
List

### ISSUE THREAD

**Issue by portapipe** [darkskyapp/skycons#20]
Why not make a very simple list of image->name ? It should be less painful to find the correct image for the right situation.
Thanks

**Comment by ironwallaby** [comment]
I'm sorry, I'm not sure I understand. There is such a list in the example web page:

```
          list  = [
            "clear-day", "clear-night", "partly-cloudy-day",
            "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
            "fog"
          ],
```

Is this what you're looking for?

**Comment by portapipe** [comment]
Hi.
I didn't know "sleet" what icon was, so I thought if you can make a simple list like:
[sun-image] clear-day
[moon-image] clear-night
[rain-image] rain
and so on...

Simple as that 😃

**Comment by ironwallaby** [comment]
That's a good suggestion. I'll make a note of it and try to get to it as time permits!

For whatever it's worth in the meantime, that list corresponds to [this page](https://darkskyapp.github.io/skycons/), from left-to-right and top-to-bottom. (Sleet is between the rain and snow icons: it's the precipitation with the straight lines falling.)

**Comment by portapipe** [comment]
Thanks! Here in italy we have the sun with rainy clouds too, like today in Milan: sun half of the day with the other half of rain.
Nice script btw

**Comment by ghost** [comment]
**Skycons** is no longer maintained; please fork to do any further work on it!
