### ISSUE TITLE
Please mention the number of icons it is supporting.

### ISSUE THREAD

**Issue by binoysarker** [darkskyapp/skycons#26]
Hello sir, I am trying to use https://api.weather.gov/ api , but there are not enough icons to show. Please let know and i can not get the how many icons are there and their little description.

**Comment by ironwallaby** [comment]
The complete list of icons may be viewed at http://darkskyapp.github.io/skycons/

In code, the list is:

```
clear-day
clear-night
partly-cloudy-day
partly-cloudy-night
cloudy
rain
sleet
snow
wind
fog
```
