### ISSUE TITLE
Changing the icon colors

### ISSUE THREAD

**Issue by Michael-Lafreniere** [darkskyapp/skycons#27]
Is there any way to change the color of the icons once they're created?  With themed sites being very common these days it seems an oversight to not have this ability.  Nor do I mean individually coloring the icons either.

**Comment by ironwallaby** [comment]
You can set the color property of the Skycons instance that you create, which will change the color of icons in that batch from then on:

```
var skycons = new Skycons({"color": "pink"});
...
skycons.color = "blue";
```
