### ISSUE TITLE
Skycons animation consuming constantly 100% CPU in Chromium

### ISSUE THREAD

**Issue by aldipower** [darkskyapp/skycons#31]
Hi, just wondered why my project is consuming constantly 100% of CPU (single core) and also some GPU in Chromium (newest build - April 4th 2020).
I could determine the Skycons, hanging in the requestAnimationFrame-loop. I can reproduce it.
Not sure what is going on exactly though. Firefox does not have any problems with it.

Two screenshot from the Chromium profiler:
![Bildschirmfoto_2020-04-06_20-02-57](https://user-images.githubusercontent.com/859154/78590681-7ab3cd80-7842-11ea-976e-abdd8826c657.png)
![Bildschirmfoto_2020-04-06_20-04-42](https://user-images.githubusercontent.com/859154/78590684-7b4c6400-7842-11ea-9548-9bb9d335a8ae.png)

**Comment by aldipower** [comment]
Okay, this really seems to be browser related and not a bug by the Skycons itself.
Interestingly, this is my CPU consumption with animation turned on by the Skycons in different browser - same platform (Ubuntu):
Chromium - 100%
Chrome - ~17%
Firefox - ~1%

Maybe something with hardware accerlation, dunno, but hey, these are only small icons here. Nothing special.. Not sure why Chromium is freaking out, I should file a bugreport there.

**Comment by ghost** [comment]
My guess is that this is determined by how the platform schedules `requestAnimationFrame`: I assume Firefox is being clever to minimize refreshes, Chrome is not (but not being too bad about it), whereas Chromium is just running frames as often as it can (regardless of whether or not it makes sense to run a tiny icon at 300 frames per second).

But that's just a guess. This library is no longer actively maintained at Dark Sky, so I'm afraid we're going to have to leave this for the community to investigate!

**Comment by aldipower** [comment]
Sounds reasonable, but unproofed. :)
For the records:
https://bugs.chromium.org/p/chromium/issues/detail?id=1068560

**Comment by ghost** [comment]
**Skycons** is no longer maintained; please fork to do any further work on it!
